### ISSUE TITLE
Authentication does not work when running development server

### ISSUE THREAD

**Issue by jblehr** [OutdoorRD/trails-viz#211]
When running the dashboard in `dev` mode, following the instructions [here](https://github.com/OutdoorRD/trails-viz/wiki/Development), I encountered an error when trying to submit my password for logging in. Because of this, we are unable to test any new data to be displayed on the dashboard that is behind the login (e.g., visitor characteristics data). Here's the error:

```
127.0.0.1 - - [16/Aug/2024 11:54:37] "POST /api/users/authenticate HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/jblehr/ord/git/trails-viz/trails-viz-api/trailsvizapi/controller/users_controller.py", line 46, in authenticate_user
    user_json = users_repository.get_user_json(username)
  File "/Users/jblehr/ord/git/trails-viz/trails-viz-api/trailsvizapi/repository/users_repository.py", line 28, in get_user_json
    bucket = _bucket_reference()
  File "/Users/jblehr/ord/git/trails-viz/trails-viz-api/trailsvizapi/repository/users_repository.py", line 14, in _bucket_reference
    storage_client = storage.Client()
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/google/cloud/storage/client.py", line 94, in __init__
    project=project, credentials=credentials, _http=_http
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/google/cloud/client.py", line 226, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/google/cloud/client.py", line 178, in __init__
    project = self._determine_default(project)
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/google/cloud/client.py", line 193, in _determine_default
    return _determine_default_project(project)
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/Users/jblehr/ord/git/trails-viz/viz-env/lib/python3.7/site-packages/google/auth/_default.py", line 321, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

It seems like there may be some credentials/other variables available when this is run on the GCP vs. locally. Based on the docs [here](https://github.com/OutdoorRD/trails-viz/wiki/Docker-Image-Info#environment-variables), it appears we may need to define some other environmental variables.

I'd propose fixing this in some way so that the development server can also use/test the login function and the data behind it.

**Comment by jblehr** [comment]
This has been fixed by the addition of the `GOOGLE_APPLICATION_CREDENTIALS` environmental variable in the wiki [here](https://github.com/OutdoorRD/trails-viz/wiki/Development#backend-setup).
