### ISSUE TITLE
DOI_PIL key error

### ISSUE THREAD

**Issue by woodsp** [OutdoorRD/trails-viz#93]
[2019-12-29 17:09:33,113] ERROR in app: Exception on /api/sites/140/homeLocationsDemographics [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/dist-packages/trailsvizapi/controller/home_locations.py", line 57, in get_home_locations_demographics
    data = home_locations.get_demographic_summary(siteid)
  File "/usr/local/lib/python3.7/dist-packages/trailsvizapi/repository/home_locations.py", line 172, in get_demographic_summary
    census_tract_states = app_config.CENSUS_TRACT_STATES[project]
KeyError: 'DOI_PIL'

**Comment by vivekkr12** [comment]
The `Prjct_code` for DOI in the geojson file is `DOI_PIL`. So we have to either update the geojson file or rename the project and readme file from `DOI` to `DOI_PIL` in the API. Which one is preferable?
